//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_CSharp
{


    public partial class UserSearch
    {
         /// <summary>
    /// UpdatePanel1 control.
    /// </summary>
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;

    /// <summary>
    /// UpdateProgress1 control.
    /// </summary>
    protected global::System.Web.UI.UpdateProgress UpdateProgress1;

    /// <summary>
    /// lblTituloProrroga control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblTituloProrroga;

    /// <summary>
    /// lblNroProrroga control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblNroProrroga;

    /// <summary>
    /// lblRazonSocial control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblRazonSocial;

    /// <summary>
    /// lblCUITDetalle control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblCUITDetalle;

    /// <summary>
    /// lblFecha control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblFecha;

    /// <summary>
    /// lblfechaAprob control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblfechaAprob;

    /// <summary>
    /// lblEstado control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblEstado;

    /// <summary>
    /// hlnkDetalle control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink hlnkDetalle;

    /// <summary>
    /// imgBarCode control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Image imgBarCode;

    /// <summary>
    /// lblCUIT control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblCUIT;

    /// <summary>
    /// ddEstadoTramitesFiltro control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList ddEstadoTramitesFiltro;

    /// <summary>
    /// txtNro control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtNro;

    /// <summary>
    /// txtCUIT control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtCUIT;

    /// <summary>
    /// Accion control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList Accion;

    /// <summary>
    /// cmdBuscar control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button cmdBuscar;

    /// <summary>
    /// lblCount control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblCount;

    /// <summary>
    /// gvTramites control.
    /// </summary>
    protected global::System.Web.UI.WebControls.GridView gvTramites;

    /// <summary>
    /// cmdMisDDJJ control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button cmdMisDDJJ;

    /// <summary>
    /// cmdAdminDDJJ control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button cmdAdminDDJJ;

    /// <summary>
    /// cmdExportarResumen control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button cmdExportarResumen;
    }
}
