//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_CSharp
{


    public partial class SignIn
    {
        /// <summary>
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        protected global::System.Web.UI.WebControls.TextBox TextBox0;

        /// <summary>
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        protected global::System.Web.UI.WebControls.TextBox TextBox1;


        /// <summary>
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        protected global::System.Web.UI.WebControls.TextBox TextBox2;
    }
}
